### ISSUE TITLE
Unable to run compath populate

### ISSUE THREAD

**Issue by bigsuicideparty** [ComPath/ComPath#88]
I succesfully installed compath.

When I run the command "python3 -m compath populate" I geet the follwoing error:

Traceback (most recent call last):
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/compath/__main__.py", line 5, in <modul
e>
    from compath.cli import main
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/compath/cli.py", line 12, in <module>
    from flask_security import SQLAlchemyUserDatastore
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/flask_security/__init__.py", line 13, i
n <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/flask_security/core.py", line 28, in <m
odule>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/flask_security/forms.py", line 17, in <
module>
    from flask_wtf import FlaskForm as BaseForm
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/flask_wtf/__init__.py", line 17, in <mo
dule>
    from .recaptcha import *
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/flask_wtf/recaptcha/__init__.py", line 
2, in <module>
    from .fields import *
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/flask_wtf/recaptcha/fields.py", line 3,
 in <module>
    from . import widgets
  File "/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8/site-packages/flask_wtf/recaptcha/widgets.py", line 5
, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/home/felix_beulig_unibt/miniconda2/envs/kegg/lib/python3.8
/site-packages/werkzeug/__init__.py)

**Comment by cthoyt** [comment]
Hi @bigsuicideparty we're about to push 5 big PR's that should solve some of the previous issues:

- [x] https://github.com/bio2bel/kegg/pull/14
- [x] https://github.com/bio2bel/reactome/pull/17
- [x] https://github.com/bio2bel/wikipathways/pull/11
- [x] https://github.com/bio2bel/msig/pull/4

And then ultimately https://github.com/ComPath/ComPath/pull/89

**Comment by ddomingof** [comment]
@bigsuicideparty can you please check
